[package]
name = "blink-one"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/elmarx/blink1-rs"

[dependencies]
hidapi = { version = "2.6.7", default-features = false, features = ["linux-native-basic-udev"] }

[features]
default = []
# expos the "low level" commands directly
commands = []
